config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root 'home#index'
  resources :albums 
  
  delete "images/:id/purge", to: "albums#purge", as: "purge_image"
  get 'tags/:tag', to: 'home#index', as: "tag"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  
  has_many_attached :images
  has_one_attached :cover_image

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  belongs_to :user

  def self.tagged_with(name)
    Tag.find_by_name!(name: name).albums
  end
  
  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    tags.map(&:name).join(", ")
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :albums, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :album
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :albums
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action :authenticate_user!, except: [:show, :index]

  before_action :correct_user, only: [:edit, :update, :destroy]


  def index
    @albums = current_user.albums if current_user.present?

    @q = @albums.ransack(params[:q])
    @albums = @q.result.includes(:tags)
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    
    if @album.save
      redirect_to @album, notice: "Album was succesfully created"
      
    else
      render :new
    end

  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to @album, notice: "Album was succesfully updated"
    else
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    redirect_to albums_path, notice: "Album was succesfully destroyed"
  end

  def purge
     image = ActiveStorage::Attachment.find(params[:id])
     image.purge
     redirect_back fallback_location: root_path, notice: "the image was deleted successfully"
  end

  def correct_user
    @album = current_user.albums.find_by(id: params[:id])
    redirect_to new_album_path, notice: "you are not correct user" if @album.nil?
  end

  private
    def album_params
      params.require(:album).permit(:title, :description, :user_id, :all_tags, :published, :cover_image, :images => [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to albums_path
    end
    
    
    if params[:tag]
      @albums = Album.tagged_with(params[:tag])
    else
      @albums = Album.where(published: true)
    end

    
    @q = Album.where(published: true).ransack(params[:q])
    @albums = @q.result.includes(:tags)

    #@albums = Album.where(published: true)
    #@albums = current_user.albums if current_user.present?
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/albums/_addimage.html.erb
    <%= form_with model: album do |form| %>
      <div class="field ">
            <%= form.label :Add_image %>
            <%= form.file_field :images ,:multiple => true, class: "form-control" %>
      </div><br>
      <div>
        <%= form.submit "Add image", class: "btn btn-primary" %>
      </div>
    <% end %>
 

app/views/albums/_form.html.erb
<div class="card"> 
  <div class="card-body">
    <%= form_with model: album do |form| %>
      <% if album.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(album.errors.count, "error") %> prohibited this friend from being saved:</h2>
          <ul>
            <% album.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field form-group">
      <%= form.text_field :title, class: "form-control", placeholder: "Title" %>
    </div><br>

    <div class="field ">
      <%= form.label :cover_image %>
      <%= form.file_field :cover_image, class: "form-control" %>
    </div><br>

    <div class="field form-group"> 
      <%= form.text_area :description, class: "form-control", placeholder: "Description" %>
      
    </div>

    <div class="field "> 
      <%= form.number_field :user_id, id: :album_user_id, class: "form-control", value: current_user.id, type: :hidden %>
    </div><br>

    <div class="field ">
      <%= form.label :image %>
      <%= form.file_field :images ,:multiple => true, class: "form-control" %>
    </div><br>

    <div class="field form-group">
      <%= form.text_field :all_tags, class: "form-control", placeholder: "Tags" %>
    </div><br>

    <div class="field ">
      <%= form.label :publish %>
      <%= form.check_box :published %>
    </div><br>

    <div>
      <%= form.submit class: "btn btn-dark" %>
    </div>
  <% end %>
  </div>
</div>

app/views/albums/edit.html.erb
<div class="card-header text-center">
<h2>Edit</h2>
</div>
<%= render 'form', album: @album %>

app/views/albums/index.html.erb
<div class="input-group d-flex justify-content-center mt-4">
  <div id="search-autocomplete" class="form-outline">
    <%= search_form_for @q do |f|%>
      <%= f.search_field :tags_name_eq, placeholder: "search by tags", id:"form1", class: "form-control" %>
  </div>
      <%= f.submit class: "btn btn-primary" %>
    <% end %>
</div>

<div class="row mt-4">
  <div class="text-center">
    <h3>ALBUMS</h3>
  </div>
  <% @albums.each do |album| %>
  <div class="col-md-4">
    <div class="card">
      <div class="card-header text-center">
        <h5><%= album.title %></h5>
      </div>
      <div class="card-body m-0 p-0">
        <%= link_to image_tag(album.cover_image, class: "img-fluid"), album_path(album) %><br>
      </div>
      <div class="card-body">
        <h6 class="card-text"><%= album.description %></h6><br>
        <div class="button d-flex justify-content-center">
        <%= link_to 'edit', edit_album_path(album), class: "btn btn-dark" %>&#160 &#160
        <%= link_to 'destroy', album_path(album), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
      </div>
      </div>
    </div>
    <br>
    </div>
  <% end %>
</div>
<br>
<div class="d-flex justify-content-center">
  <%= link_to 'Create new album', new_album_path, class: "btn btn-success" %>
</div><br>   

app/views/albums/new.html.erb
<div class="card mt-4 mb-2 border-dark">
  <div class="title text-center mt-2 mb-2">
    <h3>New Album</h3>
  </div>
</div>
  <%= render 'form', album: @album %><br><br><br>

app/views/albums/show.html.erb
<div class="row mt-2">
  <div class="text-center">
    <h3>IMAGES</h3>
  </div>
    <% @album.images.each do |image|%>    
      <div class="col-md-4">
        <div class="card mt-4 mb-4">
          <div class='card-body m-0 p-0'>
            <%= image_tag(image,class:'img-fluid') %><br>  
          </div>
          <% if current_user.present? %>
          <div class="card-footer">
              <%= link_to purge_image_path(image), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" do %>
                <i class="fas fa-trash"></i>
              <% end %>
              <%= link_to image, target: "_blank" do %>
                <i class="fas fa-search-plus float-end fa-lg mt-2"></i>
              <% end %>
          </div> 
          <% end %>
        </div> 
      </div>
    <% end %>
</div>
<% if current_user.present? %>
  <%= render 'addimage', album: @album %>
<% end %>
<div class="d-flex justify-content-center mb-4">
  <% if current_user.present? %>
    <%= link_to 'Back to albums', albums_path, class: "btn btn-dark "  %>&#160
  <% else %>
    <%= link_to 'Back', root_path, class: "btn btn-dark" %>
  <% end %>
  <%= link_to 'edit album', edit_album_path(@album), class: "btn btn-success " %>&#160
  <% if current_user.present? %>
    <%= link_to 'destroy album', album_path(@album), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
  <% end %>
</div>

app/views/home/_footer.html.erb
<footer class="bg-dark text-white pt-5 pb-4">
        <div class="container text-center text-md-left">
            <div class="row text-center text-md-left">
                <div class="col-md-3 col-lg-3 mx-auto mt-3">
                    <h3>Download Our App</h3>
                <div class="app-logo">
                    <a href="https://play.google.com/store"><%= image_tag('playstore.png', style: "height:3rem") %></a>
                    <a href="https://www.indiaistore.com/"><%= image_tag('app-store.png', style: "height:3rem") %></a>
                </div>
                </div>
                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
                    <h3>Follow Us</h3>
                <ul style="list-style-type: none;" class="d-flex justify-content-center "> 
                    <li><a href="https://www.facebook.com" type="button"><i class="fab fa-facebook p-2 fa-2x"></i></a></li>
                    <li><a href="https://www.instagram.com" type="button"><i class=" fab fa-instagram p-2 fa-2x"></i></a></li>
                    <li><a href="https://www.twitter.com" type="button"><i class=" fab fa-twitter p-2 fa-2x"></i></a></li>
                    <li><a href="https://www.youtube.com" type="button"><i class=" fab fa-youtube p-2 fa-2x"></i></a></li>
                </ul>
                </div>
            </div>
            <hr class="mb-4">
            <div class="row align-items-center justify-content-center" style="text-align: center;">
                <div class="col-md-7 col-lg-8 flex-row d-flex  justify-content-center">
                    <p>copyright 2021 All rights reserved by: &#160;</p>
                    <a href="https://www.linkedin.com/in/arvind-jangir-749a87179/" class="text-success">
                        <b class="text-success" style="text-decoration: none;">Arvind Jangir</b>
                    </a>
                </div> 
            </div>
        </div>
</footer>

app/views/home/_header.html.erb
<!--<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Gallery</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">  
        <% if user_signed_in? %>  
          <li class="nav-item">
            <%= link_to 'My Albums',albums_path, class:'nav-link' %> 
          </li>
          <li class="nav-item">
            <%= link_to 'New Album',new_album_path, class:'nav-link ' %> 
          </li>
          <li class="nav-item ">
            <%= link_to 'Sign-Out',destroy_user_session_path, method: :delete, class:'nav-link ' %> 
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile',edit_user_registration_path, class:'nav-link ' %> 
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Home',root_path, class:'nav-link' %> 
          </li>  
            <li class=" nav-item  ">
              <%= link_to 'Sign-In',new_user_session_path, class:'nav-link' %> 
            </li>
            <li class="nav-item ">
              <%= link_to 'Sign-up',new_user_registration_path, class:'nav-link' %> 
            </li>
        <% end %>
     </ul>
    </div>
  </div>
</nav>-->


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Gallery", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse fw-bold" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">  
        <% if user_signed_in? %>  
          <li class="nav-item">
            <%= link_to 'My Albums',albums_path, class:'nav-link' %> 
          </li>
          <li class="nav-item">
            <%= link_to 'New Album',new_album_path, class:'nav-link ' %> 
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile',edit_user_registration_path, class:'nav-link ' %> 
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Home',root_path, class:'nav-link' %> 
          </li>  
          
        <% end %>
     </ul>

      <ul class="navbar-nav mb-2 mb-lg-0">
        <% if user_signed_in? %>
        <p class="mt-2 text-white">Signed in as:-</p>
          <%= link_to current_user.email, edit_user_registration_path, class: "active nav-item nav-link fw-bold" %>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-item nav-link btn btn-danger mb-1 text-white fw-bold" %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-item nav-link text-white " %>
          <%= link_to "Sign-in", new_user_session_path, class: "nav-item nav-link btn btn-primary text-white fw-bold" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/_search.html.erb
<div class="input-group d-flex justify-content-center">
  <div id="search-autocomplete" class="form-outline">
    
    <%= search_form_for @q, url: root_path do |f|%>
    <%= f.search_field :tags_name_eq, placeholder: "search by tags", id:"form1", class: "form-control" %>
    
  </div>
  <%= f.submit class: "btn btn-primary" %>
    <% end %>
  
    
  
  
</div>

app/views/home/index.html.erb
<div class="search mt-4 d-flex justify-content-center">
  <%= render 'home/search' %>
</div>
<div class="row mt-4">
  <div class="text-center">
    <h3>ALBUMS</h3>
  </div>
<% @albums.each do |album| %>
  <div class="col-md-4">
    <div class="card">
      <div class="card-header text-center">
        <h5 class="card-title"><%= album.title %></h5>
      </div>
      <div class="card-body m-0 p-0">
          <%= link_to image_tag(album.cover_image, class: "img-fluid"), album_path(album) %><br>
      </div>
      <div class="card-footer">
        <h6 class="card-text"><%= album.description %></h6><br>
      </div>
      <div class="content">
        <div class="time d-flex">
          <b>Published At:-</b><%= album.created_at.to_date %>   
        </div>
        <div class="time d-flex">
          <b>Updated At:-</b></h6><%= album.updated_at.to_date %>
        </div>
        <br>
        <div class="totalimg d-flex">
          <b>Total images:-</b><%= album.images.count %>
        </div>
        <div class="tags d-flex">
          <b>Tags</b><p><%= album.all_tags %></p>
        </div>
      </div>
    </div><br>
    
  </div>
<% end %>
</div><br>
<div class="d-flex justify-content-center">
  <%= link_to 'Create new album', new_album_path, class: "btn btn-success" %>
</div><br>

app/views/layouts/_alerts.html.erb
<div class="alert alert-success alert-dismissible fade show mt-4" role="alert">
  <strong><p><%= notice %></p></strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    <title>Gallery</title>
  </head>
  <body> 
    <%= render 'home/header' %>
    <div class="container">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'home/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>